mutation AddLocation(
  $name: String!
  $friendlyName: String!
  $description: String!
  $latitude: Float!
  $longitude: Float!
  $picture: String!
  $locationTags: [LocationTagInput!]!
) {
  addLocation(
    name: $name
    friendlyName: $friendlyName
    description: $description
    latitude: $latitude
    longitude: $longitude
    picture: $picture
    locationTags: $locationTags
  ) {
    id
    locationName
    friendlyName
    description
    latitude
    longitude
    locationOwner
    locationTags {
      description
      tagName
      id
      ownerId
    }
    needsCleaning
    pictureURI
  }
}
